apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: apache-pod
  labels: 
    app: Apache
spec: 
  minReadySeconds: 3
  replicas: 2
  selector: 
    matchLabels: 
      app: Apache
  template: 
    metadata: 
      name: apache-con
      labels: 
        app: Apache 
    spec: 
      containers: 
        - name: apache-con
          image: httpd:alpine
          ports: 
            - containerPort: 8080
              protocol: TCP

        
