apiVersion: v1
kind: Service
metadata: 
  name: apache-svc
  labels: 
    purpose: apache
spec: 
  selector: 
    app: apache
  type: NodePort
  ports: 
    - name: apacheS-svc
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30001