apiVersion: v1
kind: Service
metadata: 
  name: jenkins-svc
  labels: 
    purpose: jenkins
spec: 
  selector: 
    app: Jenkins
  type: NodePort
  ports: 
    - name: jenkins-svc
      port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 30001