apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jenkins-pod
  labels: 
    app: Jenkins 
spec: 
  minReadySeconds: 3
  replicas: 2
  selector: 
    matchLabels: 
      app: Jenkins
  template: 
    metadata: 
      name: jenkins-con
      labels: 
        app: Jenkins 
    spec: 
      containers: 
        - name: jenkins-con
          image: jenkins/jenkins:jdk11
          ports: 
            - containerPort: 8080
              protocol: TCP

        
