apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jenkins-rs
  labels:
    app: Jenkins 
spec: 
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: Jenkins
  template: 
    metadata: 
      name: jenkins-pods 
      labels: 
        app: Jenkins 
    spec: 
      containers: 
       - name: jenkins 
         image: jenkins:2.60.3 
         ports: 
          - containerPort: 8080
            protocol: TCP
