apiVersion: v1
kind: Service 
metadata: 
  name: jenkins-svc
  labels: 
    app: Jenkins
spec: 
  selector:
    app: Jenkins 
  type: LoadBalancer
  ports: 
    - name: jenkins-svc
      targetPort: 8080
      port: 80
      protocol: TCP
