apiVersion: v1
kind: Service
metadata: 
  name: apache-svc
  labels: 
    for: apache-rs
spec: 
  selector: 
    app: Apache
  type: LoadBalancer
  ports: 
    - port: 4856
      targetPort: 80
      protocol: TCP

